apiVersion: v1
kind: Secret
metadata:
  name: cs-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "ACCESSKEYFALSA"
  AWS_SECRET_ACCESS_KEY: "SECRETKEYFALSA"
  AWS_SESSION_TOKEN: "SESSIONTOKENFALSO"