apiVersion: v1
kind: Secret
metadata:
  name: cs-secrets
  labels:
    project: conexao-solidaria
type: Opaque
data:

  #RabbitMq
  #F1aP.
  #F1aP.371928
  RABBITMQ_USERNAME: ZmlhcA==
  RABBITMQ_PASSWORD: ZmlhcDEyMw==

  #Usuarios-DB
  USUARIOS_POSTGRES_USER: ZmlhcA==
  USUARIOS_POSTGRES_PASSWORD: ZmlhcDEyMw==

  #Campanhas-DB
  CAMPANHAS_POSTGRES_USER: ZmlhcA==
  CAMPANHAS_POSTGRES_PASSWORD: ZmlhcDEyMw==

  #Doacoes-DB
  DOACOES_POSTGRES_USER: ZmlhcA==
  DOACOES_POSTGRES_PASSWORD: ZmlhcDEyMw==

  #JWT
  JWT_SECRETKEY: Q2hhdmVTdXBlclNlY3JldGFDb21NYWlzRGUzMkNhcmFjdGVyZXNBcXVpMTIzNDU=
  JWT_ISSUER: RVMtQ29uZXhhb1NvbGlkYXJpYUlzc3Vlcg==
  JWT_AUDIENCE: RVMtQ29uZXhhb1NvbGlkYXJpYUNsaWVudA==
  JWT_EXPIRATION_HOURS: Mw==

  #AES
  AES_KEY: VzM2dHVaZ0F3WlRrdkdlYlJNRVFKakd0YkxOSlJLNnVuR2oxT3c1Um5tOD0=
