# *********************************************************************************************************************** #
# RABBITMQ                                                                                                                #       
# *********************************************************************************************************************** #
apiVersion: v1
kind: Service
metadata:
  name: cs-rabbitmq-amqp-svc
  labels:
    app: cs-rabbitmq
    project: conexao-solidaria
spec:
  type: ClusterIP
  selector:
    app: cs-rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: cs-rabbitmq-manag-svc
  labels:
    app: cs-rabbitmq
    project: conexao-solidaria
spec:
  type: LoadBalancer
  selector:
    app: cs-rabbitmq
  ports:
    - name: management
      port: 15672
      targetPort: 15672

# *********************************************************************************************************************** #
# USUARIOS-DB                                                                                                             #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-usuarios-db-svc
  labels:
    app: cs-usuarios-db
    project: conexao-solidaria
spec:
  selector:
    app: cs-usuarios-db
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP


# *********************************************************************************************************************** #
# CAMPANHAS-DB                                                                                                            #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-campanhas-db-svc
  labels:
    app: cs-campanhas-db
    project: conexao-solidaria
spec:
  selector:
    app: cs-campanhas-db
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP


# *********************************************************************************************************************** #
# DOACOES-DB                                                                                                              #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-doacoes-db-svc
  labels:
    app: cs-doacoes-db
    project: conexao-solidaria
spec:
  selector:
    app: cs-doacoes-db
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP


# *********************************************************************************************************************** #
# DYNAMODB                                                                                                                #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-dynamo-db-svc
  labels:
    app: cs-dynamo-db
    project: conexao-solidaria
spec:
  selector:
    app: cs-dynamo-db
  type:  ClusterIP
  ports:
    - name: dynamodb
      port: 8000
      targetPort: 8000
      protocol: TCP


# *********************************************************************************************************************** #
# REDIS                                                                                                                   #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-redis-svc
  labels:
    app: cs-redis
    project: conexao-solidaria
spec:
  selector:
    app: cs-redis
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP


# *********************************************************************************************************************** #
# ELASTICSEARCH                                                                                                           #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-elasticsearch
  labels:
    app: cs-elasticsearch
    project: conexao-solidaria
spec:
  selector:
    app: cs-elasticsearch
  type: ClusterIP
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      protocol: TCP
    - name: transport
      port: 9300
      targetPort: 9300
      protocol: TCP


# *********************************************************************************************************************** #
# MAILPIT                                                                                                                 #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-mailpit-svc
  labels:
    app: cs-mailpit
    project: conexao-solidaria
spec:
  selector:
    app: cs-mailpit
  type: ClusterIP  
  ports:
    - name: smtp
      port: 1025
      targetPort: 1025
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: cs-mailpit-mgmt-svc
  labels:
    app: cs-mailpit
    project: conexao-solidaria
spec:
  selector:
    app: cs-mailpit
  type: LoadBalancer 
  ports:
    - name: webui
      port: 8025
      targetPort: 8025
      protocol: TCP


# *********************************************************************************************************************** #
# USUARIOS API                                                                                                            #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-usuarios-api-svc
  labels:
    app: cs-usuarios-api
    project: conexao-solidaria
spec:
  selector:
    app: cs-usuarios-api
  type: ClusterIP
  ports:
    - name: http
      port: 5001
      targetPort: 8080
      protocol: TCP


# *********************************************************************************************************************** #
# CAMPANHAS API                                                                                                          #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-campanhas-api-svc
  labels:
    app: cs-campanhas-api
    project: conexao-solidaria
spec:
  selector:
    app: cs-campanhas-api
  type: ClusterIP
  ports:
    - name: http
      port: 5002
      targetPort: 8080
      protocol: TCP


# *********************************************************************************************************************** #
# DONATION WORKER API                                                                                                     #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-donationworker-api-svc
  labels:
    app: cs-donationworker
    project: conexao-solidaria
spec:
  selector:
    app: cs-donationworker
  type: ClusterIP
  ports:
    - name: http
      port: 5003
      targetPort: 8080
      protocol: TCP


# *********************************************************************************************************************** #
# NOTIFICACOES    API                                                                                                     #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-notificacoes-api-svc
  labels:
    app: cs-notificacoes-api
    project: conexao-solidaria
spec:
  selector:
    app: cs-notificacoes-api
  type: ClusterIP
  ports:
    - name: http
      port: 5004
      targetPort: 8080
      protocol: TCP


# *********************************************************************************************************************** #
# GATEWAY                                                                                                                 #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-gateway-api-svc
  labels:
    app: cs-gateway-api
    project: conexao-solidaria
spec:
  selector:
    app: cs-gateway-api
  type: LoadBalancer
  ports:
    - name: http
      port: 5006
      targetPort: 8080
      protocol: TCP


# *********************************************************************************************************************** #
# PROMETHEUS                                                                                                              #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-prometheus-svc
  labels:
    app: cs-prometheus
    project: conexao-solidaria
spec:
  selector:
    app: cs-prometheus
  type: ClusterIP
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP


# *********************************************************************************************************************** #
# ZABBIX                                                                                                                  #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-zabbix-svc
  labels:
    app: cs-zabbix
    project: conexao-solidaria
spec:
  type: ClusterIP
  selector:
    app: cs-zabbix
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: trapper
      port: 10051
      targetPort: 10051
---
apiVersion: v1
kind: Service
metadata:
  name: cs-zabbix-manag-svc
  labels:
    app: cs-zabbix
    project: conexao-solidaria
spec:
  type: ClusterIP
  selector:
    app: cs-zabbix
  ports:
    - name: management
      port: 8086
      targetPort: 80


# Agent
---
apiVersion: v1
kind: Service
metadata:
  name: cs-zabbix-agent-svc
  labels:
    app: cs-zabbix-agent
    project: conexao-solidaria
spec:
  selector:
    app: cs-zabbix-agent
  ports:
    - name: agent
      port: 10050
      targetPort: 10050
  type: ClusterIP


# *********************************************************************************************************************** #
# DYNAMO PG PROXY                                                                                                         #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-dynamo-pg-proxy-svc
  labels:
    app: cs-dynamo-pg-proxy
    project: conexao-solidaria
spec:
  selector:
    app: cs-dynamo-pg-proxy
  type: ClusterIP
  ports:
    - name: http
      port: 5450
      targetPort: 5450
      protocol: TCP



# *********************************************************************************************************************** #
# GRAFANA                                                                                                                 #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-grafana-svc
  labels:
    app: cs-grafana
    project: conexao-solidaria
spec:
  selector:
    app: cs-grafana
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP


# *********************************************************************************************************************** #
# FRONTEND                                                                                                                #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: Service
metadata:
  name: cs-frontend-svc
  labels:
    app: cs-frontend
    project: conexao-solidaria
spec:
  selector:
    app: cs-frontend
  type: LoadBalancer
  ports:
    - name: http
      port: 5000
      targetPort: 80
      protocol: TCP

