apiVersion: v1
kind: Secret
metadata:
  name: cs-aws-credentials
type: Opaque
stringData:
  #####################################################################################################
  # ESSE ARQUIVO É UM PLACEHOLDER. SECRETS SAO INJETADOS VIA GITHUB ACTIONS
  #####################################################################################################

  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_SESSION_TOKEN: ""