apiVersion: v1
kind: Secret
metadata:
  name: cs-aws-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "ASIAZKPYYBDP7K2PWBMZ"
  AWS_SECRET_ACCESS_KEY: "SxTc1amCOoPP6+A1UXKNQgPm228XS/5kCKn4rxty"
  AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEO7//////////wEaCXVzLXdlc3QtMiJHMEUCIQCTVPFhbIasNe/7clg0G+l1vJpWVhmOiJ7WsBCIapDJ2gIgAstPLsOaneOQ2UovFFBuP9xtA7FSakIyg/8+W0A4hgcqtwIIt///////////ARAAGgw2NDEwMDg2NjY4NDciDMbmVLa103/J9kNGxSqLAognWb8nntOpRJC50+8LMXdGioBw0AFyA9FNImCUc4vooEfMgLAuOdGCnZlLqUJnmbknfqTk3p4czXan+E7gxb01p/yh5R/lKKij5LQ1GazDIvgJm/8C9/C36cKpSQKyuG8Tg0b2enABq659ThVUYfdu7xpxW17IBtsxS559R/KyYLg2rWQ3xkzmEIT75Rrm6iV+IoDDKxIOHNigOZWSXBGRgRqi2r6vnZvNQtr5CECw2DjM//+KI1BoS0CFMTRBWXdleULG1Slv1cQKuJu3A0vxqXQqw/jMD8H+tvsivojj9IBCAXHfWkVsZsaki0P5Ea3IOzZOBwMubYJDzjNZTO+FD+bVDDJhRGsaKzCPxYvSBjqdAY/g5kBk8CcLxebXfYnd51JKgf3NLff0LekBJzrBAUmVXIn6zxP++jKQLGZ85qb9u9xNd6pnudOXUyZFriDc9NiwDiLDK1EhHD9QWCdokqU06fejqH0h3C1P2b7qsEIMwLTaopTEEJE5UArxbcEpeTGjwMvBRUr4kdO/p7WMmrsGWMtNwG0vb/Zy7ESySQBO7HIrUYB3KGuCJWbRc4w="
