apiVersion: v1
kind: Secret
metadata:
  name: cs-aws-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "ASIAZKPYYBDPXNFIQZB3"
  AWS_SECRET_ACCESS_KEY: "wQlCOCKnUdvcgmt3fHlXb2U1kU3DhM/KXYySvmJx"
  AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEHEaCXVzLXdlc3QtMiJIMEYCIQDuRnXz5z4s9anq59eMTjyF8dmQC7EUBRV5zL8suSyIkAIhAJR+gaWjQ/Ks0kk8IXLVIBrU2W3LCIm2SZTpc/Kyhv1pKq4CCDkQABoMNjQxMDA4NjY2ODQ3IgwADttRjldq3vbsFHMqiwLUXKcEHY/Dhv52n+uwDQXbpxfiaiXIt2MkNkAMWgylUrdRLcK0FNB9AFID8OqOAgKFYvwhkqPYt5gBOUFdOBlcUjNQkbbC2Kw/O1zkbOA1zhRln/Fm7MuxWQQMM/ZyyglGZvgQBogSfVllJIEt7XlSADHmhtHnHSw+UWnixrWT8uO6B1SjIvR0u/FAVg0VbSeFLJ8OM+w9IEkTMrGNxhg9pRpo8w25pXuwsTdWkiSCQ7aMlflQ6lEzhfmR0RxqqPVGbcOkIDE0SI0M6KzShg0FtpRCdJKlI7zvZycaI63UQjgTpd9iQ/MRAXU1Ur2hKrks3c4HIF872/pCHOMH6HYDHUlOggj/SJhURU4ww4fw0QY6nAESkK1PdR/WlLmkK9mTRdBavLxN3qHE37U/nWqwRnxmeMsMZwO3dr0lZ4gU2PcEJ0hdS2MNYFcJzlNV3+K5ZsLP3l0M6dKF4kcPonod0MtqVBBPhMvyLXYT0lzRO7tzixtTXLJpi1Wl/J+irkWHWOFfr1xq1pVNcS9zcYR0wFy1F3sI1SkBHsYQdIsBMJE1CZnwaxZ5vR0UySD/1AU="
