apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-observability-config
  labels:
    app: cs-observability
    project: conexao-solidaria
data:
  # ── Arquivo de Configuração do Prometheus ────────────────────────────────
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "usuarios-api"
        static_configs:
          - targets: ["cs-usuarios-api-svc:5001"] # Corrigido para a porta 80 do Service
        metrics_path: /metrics
        scrape_interval: 10s

      - job_name: "campanhas-api"
        static_configs:
          - targets: ["cs-campanhas-api-svc:5002"] # Corrigido para a porta 80 do Service
        metrics_path: /metrics
        scrape_interval: 10s

      - job_name: "donationworker"
        static_configs:
          - targets: ["cs-donationworker-api-svc:5003"] 
        metrics_path: /metrics
        scrape_interval: 10s

      - job_name: "prometheus"
        static_configs:
          - targets: ["cs-prometheus-svc:9090"]

  # ── Arquivo de Datasource do Grafana ─────────────────────────────────────
 
  grafana_datasource_prometheus.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://cs-prometheus-svc:9090
        isDefault: true
        editable: false

      - name: Zabbix
        type: alexanderzobnin-zabbix-datasource
        access: proxy
        url: http://cs-zabbix-svc/api_jsonrpc.php
        isDefault: false
        editable: false
        jsonData:
            username: Admin
            trends: true
            trendsFrom: "7d"
            trendsRange: "4d"
            cacheTTL: "1h"
            dbConnectionEnable: false
        secureJsonData:
          password: zabbix


      - name: DynamoDB-PG
        uid: dynamo-pg
        type: postgres
        url: cs-dynamo-pg-proxy-svc:5450
        user: grafana
        database: dynamo
        isDefault: false
        editable: false
        jsonData:
            sslmode: disable
            postgresVersion: 1400
        secureJsonData:
          password: grafana

  
  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: 'Default Provider'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards