apiVersion: v1
kind: Secret
metadata:
  name: cs-secrets
  labels:
    project: conexao-solidaria
type: Opaque
data:
  #####################################################################################################
  # ESSE ARQUIVO É UM PLACEHOLDER. SECRETS SAO INJETADOS VIA GITHUB ACTIONS
  #####################################################################################################

  #RabbitMq
  RABBITMQ_USERNAME: 
  RABBITMQ_PASSWORD: 

  #Usuarios-DB
  USUARIOS_POSTGRES_USER: 
  USUARIOS_POSTGRES_PASSWORD: 

  #Campanhas-DB
  CAMPANHAS_POSTGRES_USER: 
  CAMPANHAS_POSTGRES_PASSWORD: 

  #Doacoes-DB
  DOACOES_POSTGRES_USER: 
  DOACOES_POSTGRES_PASSWORD: 

  #JWT
  JWT_SECRETKEY: 
  JWT_ISSUER:
  JWT_AUDIENCE: 
  JWT_EXPIRATION_HOURS: 

  #AES
  AES_KEY: 
