# *********************************************************************************************************************** #
# VOLUME                                                                                                                #       
# *********************************************************************************************************************** #
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cs-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # Nome customizado para ignorar a AWS
  hostPath:
    path: "/mnt/data"


# *********************************************************************************************************************** #
# ELASTICSEARCH                                                                                                           #       
# *********************************************************************************************************************** #
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-elasticsearch-pvc
spec:
  storageClassName: ""
  volumeName: cs-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi